# Generated by Django 5.2.4 on 2025-08-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('lien_du_profile', models.URLField(max_length=500)),
                ('certificats', models.TextField(blank=True)),
                ('competences', models.TextField(blank=True)),
                ('le_bot_qui_a_trouve_ce_profil', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_trouve', models.DateTimeField(auto_now_add=True)),
                ('origine_du_profil', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
